#!/usr/bin/python3.7
# -*-coding:Utf-8 -*

life = 8

liste = ["ANGLE", \
            "ARMOIRE", \
            "BANC", \
            "BUREAU", \
            "CABINET", \
            "CARREAU", \
            "CHAISE", \
            "CLASSE", \
            "CLEF", \
            "COIN", \
            "COULOIR", \
            "DOSSIER", \
            "EAU", \
            "ECOLE", \
            "ENTRER", \
            "ESCALIER", \
            "ETAGERE", \
            "FENETRE", \
            "LAVABO", \
            "LIT", \
            "MARCHE", \
            "MATELAS", \
            "MEUBLE", \
            "MOUSSE", \
            "MUR", \
            "PELUCHE", \
            "PLACARD", \
            "PLAFOND", \
            "PORTE", \
            "POUBELLE", \
            "RAMPE", \
            "RIDEAU", \
            "ROBINET", \
            "SALLE", \
            "SALON", \
            "SERRURE", \
            "SIEGE", \
            "SIESTE", \
            "SILENCE", \
            "SOL", \
            "SOMMEIL", \
            "SONNETTE", \
            "SORTIE", \
            "TABLE", \
            "TABLEAU", \
            "TABOURET", \
            "TAPIS", \
            "TIROIR", \
            "TOILETTE", \
            "VITRE", \
            "ALLER", \
            "AMENER", \
            "APPORTER", \
            "APPUYER", \
            "ATTENDRE", \
            "BAILLER", \
            "COUCHER", \
            "DORMIR", \
            "ECLAIRER", \
            "EMMENER", \
            "EMPORTER", \
            "ENTRER", \
            "FERMER", \
            "FRAPPER", \
            "LEVER", \
            "OUVRIR", \
            "PRESSER", \
            "RESTER", \
            "SONNER", \
            "SORTIR", \
            "VENIR", \
            "ABSENT", \
            "ASSIS", \
            "BAS", \
            "HAUT", \
            "PRESENT", \
            "GAUCHE", \
            "DROITE", \
            "DEBOUT", \
            "DEDANS", \
            "DEHORS", \
            "FACE", \
            "LOIN", \
            "PRES", \
            "TARD", \
            "TOT", \
            "APRES", \
            "AVANT", \
            "CONTRE", \
            "DANS", \
            "DE", \
            "DERRIERE", \
            "DEVANT"]
